import { NextResponse, type NextRequest } from 'next/server'
import { verifyToken } from '@/lib/modules/statements/statement-verify'
import { getStatementById } from '@/lib/modules/statements/statement-generation'
import { formatAUD } from '@/lib/shared/currency'
import { formatDateAU } from '@/lib/shared/dates'
import type { StatementLineItem } from '@/lib/modules/statements/statement-generation'

/**
 * Public endpoint — authenticated via JWT token in query string.
 * Returns an HTML view of the statement for SMS recipients who verified their DOB.
 */
export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
): Promise<NextResponse> {
  try {
    const { id } = await params
    const { searchParams } = new URL(request.url)
    const token = searchParams.get('token')

    if (!token) {
      return NextResponse.json(
        { error: 'Token required', code: 'UNAUTHORIZED' },
        { status: 401 }
      )
    }

    // Verify the token
    const payload = verifyToken(token)
    if (payload.statementId !== id) {
      return NextResponse.json(
        { error: 'Token does not match statement', code: 'FORBIDDEN' },
        { status: 403 }
      )
    }

    const statement = await getStatementById(id)
    if (!statement) {
      return NextResponse.json(
        { error: 'Statement not found', code: 'NOT_FOUND' },
        { status: 404 }
      )
    }

    const lineItems = statement.lineItems as unknown as StatementLineItem[]

    // Build a simple HTML page
    const lineRows = lineItems
      .map(
        (item) => `
      <tr>
        <td style="padding:6px 10px;border-bottom:1px solid #eee;">${formatDateAU(new Date(item.date))}</td>
        <td style="padding:6px 10px;border-bottom:1px solid #eee;">${escapeHtml(item.providerName)}</td>
        <td style="padding:6px 10px;border-bottom:1px solid #eee;">${escapeHtml(item.invoiceNumber)}</td>
        <td style="padding:6px 10px;border-bottom:1px solid #eee;text-align:right;">${formatAUD(item.invoicedCents)}</td>
        <td style="padding:6px 10px;border-bottom:1px solid #eee;">${item.claimStatus}</td>
        <td style="padding:6px 10px;border-bottom:1px solid #eee;text-align:right;">${formatAUD(item.paidCents)}</td>
      </tr>`
      )
      .join('')

    const html = `<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Your Statement</title></head>
<body style="font-family:Arial,sans-serif;color:#333;max-width:800px;margin:0 auto;padding:20px;">
  <h1 style="color:#059669;">Lotus Assist - Plan Statement</h1>
  <p><strong>Participant:</strong> ${escapeHtml(statement.participant.firstName)} ${escapeHtml(statement.participant.lastName)}</p>
  <p><strong>Period:</strong> ${formatDateAU(statement.periodStart)} - ${formatDateAU(statement.periodEnd)}</p>

  <div style="background:#f8f9fa;border-radius:8px;padding:20px;margin:20px 0;">
    <h3 style="margin-top:0;">Summary</h3>
    <p>Total Invoiced: <strong>${formatAUD(statement.totalInvoicedCents)}</strong></p>
    <p>Total Claimed: <strong>${formatAUD(statement.totalClaimedCents)}</strong></p>
    <p>Total Paid: <strong>${formatAUD(statement.totalPaidCents)}</strong></p>
    <p style="border-top:2px solid #ccc;padding-top:8px;">Budget Remaining: <strong style="color:#059669;">${formatAUD(statement.budgetRemainingCents)}</strong></p>
  </div>

  ${
    lineItems.length > 0
      ? `<h3>Invoice Details</h3>
  <table style="width:100%;border-collapse:collapse;">
    <thead>
      <tr style="background:#f0f0f0;">
        <th style="padding:8px 10px;text-align:left;">Date</th>
        <th style="padding:8px 10px;text-align:left;">Provider</th>
        <th style="padding:8px 10px;text-align:left;">Invoice #</th>
        <th style="padding:8px 10px;text-align:right;">Amount</th>
        <th style="padding:8px 10px;text-align:left;">Status</th>
        <th style="padding:8px 10px;text-align:right;">Paid</th>
      </tr>
    </thead>
    <tbody>${lineRows}</tbody>
  </table>`
      : '<p>No invoices for this period.</p>'
  }

  <p style="margin-top:30px;color:#999;font-size:12px;">Generated by Lotus Assist Pty Ltd. Contact your plan manager with any questions.</p>
</body>
</html>`

    return new NextResponse(html, {
      status: 200,
      headers: { 'Content-Type': 'text/html; charset=utf-8' },
    })
  } catch (error) {
    if (error instanceof Error && (error.message === 'Token expired' || error.message === 'Invalid token signature' || error.message === 'Invalid token format')) {
      return NextResponse.json(
        { error: 'Invalid or expired token', code: 'UNAUTHORIZED' },
        { status: 401 }
      )
    }
    return NextResponse.json(
      { error: 'Internal server error', code: 'INTERNAL_ERROR' },
      { status: 500 }
    )
  }
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}
